// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/chat.proto

package com.depromeet.warmup.grpc.service;

public final class ChatOuterClass {
  private ChatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022service/chat.proto\022\016warmup.service\032\033go" +
      "ogle/protobuf/empty.proto\032\016vo/int64.prot" +
      "o28\n\004Chat\0220\n\004Send\022\026.google.protobuf.Empt" +
      "y\032\020.warmup.vo.Int64B#\n!com.depromeet.war" +
      "mup.grpc.serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.depromeet.warmup.grpc.vo.Int64OuterClass.getDescriptor(),
        });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.depromeet.warmup.grpc.vo.Int64OuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
