// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Item.proto

package com.depromeet.warmup.grpc.service;

public final class ItemOuterClass {
  private ItemOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SaveRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:warmup.service.SaveRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>repeated string image_urls = 3;</code>
     * @return A list containing the imageUrls.
     */
    java.util.List<java.lang.String>
        getImageUrlsList();
    /**
     * <code>repeated string image_urls = 3;</code>
     * @return The count of imageUrls.
     */
    int getImageUrlsCount();
    /**
     * <code>repeated string image_urls = 3;</code>
     * @param index The index of the element to return.
     * @return The imageUrls at the given index.
     */
    java.lang.String getImageUrls(int index);
    /**
     * <code>repeated string image_urls = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the imageUrls at the given index.
     */
    com.google.protobuf.ByteString
        getImageUrlsBytes(int index);

    /**
     * <code>string place = 4;</code>
     * @return The place.
     */
    java.lang.String getPlace();
    /**
     * <code>string place = 4;</code>
     * @return The bytes for place.
     */
    com.google.protobuf.ByteString
        getPlaceBytes();

    /**
     * <code>.warmup.type.Categories category = 5;</code>
     * @return The enum numeric value on the wire for category.
     */
    int getCategoryValue();
    /**
     * <code>.warmup.type.Categories category = 5;</code>
     * @return The category.
     */
    com.depromeet.warmup.grpc.type.CategoryType.Categories getCategory();

    /**
     * <code>string tag = 6;</code>
     * @return The tag.
     */
    java.lang.String getTag();
    /**
     * <code>string tag = 6;</code>
     * @return The bytes for tag.
     */
    com.google.protobuf.ByteString
        getTagBytes();
  }
  /**
   * Protobuf type {@code warmup.service.SaveRequest}
   */
  public  static final class SaveRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:warmup.service.SaveRequest)
      SaveRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SaveRequest.newBuilder() to construct.
    private SaveRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SaveRequest() {
      name_ = "";
      description_ = "";
      imageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      place_ = "";
      category_ = 0;
      tag_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SaveRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SaveRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                imageUrls_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              imageUrls_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              place_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              category_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              tag_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          imageUrls_ = imageUrls_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_SaveRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_SaveRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest.class, com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_URLS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList imageUrls_;
    /**
     * <code>repeated string image_urls = 3;</code>
     * @return A list containing the imageUrls.
     */
    public com.google.protobuf.ProtocolStringList
        getImageUrlsList() {
      return imageUrls_;
    }
    /**
     * <code>repeated string image_urls = 3;</code>
     * @return The count of imageUrls.
     */
    public int getImageUrlsCount() {
      return imageUrls_.size();
    }
    /**
     * <code>repeated string image_urls = 3;</code>
     * @param index The index of the element to return.
     * @return The imageUrls at the given index.
     */
    public java.lang.String getImageUrls(int index) {
      return imageUrls_.get(index);
    }
    /**
     * <code>repeated string image_urls = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the imageUrls at the given index.
     */
    public com.google.protobuf.ByteString
        getImageUrlsBytes(int index) {
      return imageUrls_.getByteString(index);
    }

    public static final int PLACE_FIELD_NUMBER = 4;
    private volatile java.lang.Object place_;
    /**
     * <code>string place = 4;</code>
     * @return The place.
     */
    public java.lang.String getPlace() {
      java.lang.Object ref = place_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        place_ = s;
        return s;
      }
    }
    /**
     * <code>string place = 4;</code>
     * @return The bytes for place.
     */
    public com.google.protobuf.ByteString
        getPlaceBytes() {
      java.lang.Object ref = place_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        place_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 5;
    private int category_;
    /**
     * <code>.warmup.type.Categories category = 5;</code>
     * @return The enum numeric value on the wire for category.
     */
    public int getCategoryValue() {
      return category_;
    }
    /**
     * <code>.warmup.type.Categories category = 5;</code>
     * @return The category.
     */
    public com.depromeet.warmup.grpc.type.CategoryType.Categories getCategory() {
      @SuppressWarnings("deprecation")
      com.depromeet.warmup.grpc.type.CategoryType.Categories result = com.depromeet.warmup.grpc.type.CategoryType.Categories.valueOf(category_);
      return result == null ? com.depromeet.warmup.grpc.type.CategoryType.Categories.UNRECOGNIZED : result;
    }

    public static final int TAG_FIELD_NUMBER = 6;
    private volatile java.lang.Object tag_;
    /**
     * <code>string tag = 6;</code>
     * @return The tag.
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      }
    }
    /**
     * <code>string tag = 6;</code>
     * @return The bytes for tag.
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      for (int i = 0; i < imageUrls_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, imageUrls_.getRaw(i));
      }
      if (!getPlaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, place_);
      }
      if (category_ != com.depromeet.warmup.grpc.type.CategoryType.Categories.FOOD.getNumber()) {
        output.writeEnum(5, category_);
      }
      if (!getTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tag_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < imageUrls_.size(); i++) {
          dataSize += computeStringSizeNoTag(imageUrls_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getImageUrlsList().size();
      }
      if (!getPlaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, place_);
      }
      if (category_ != com.depromeet.warmup.grpc.type.CategoryType.Categories.FOOD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, category_);
      }
      if (!getTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tag_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest)) {
        return super.equals(obj);
      }
      com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest other = (com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getImageUrlsList()
          .equals(other.getImageUrlsList())) return false;
      if (!getPlace()
          .equals(other.getPlace())) return false;
      if (category_ != other.category_) return false;
      if (!getTag()
          .equals(other.getTag())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (getImageUrlsCount() > 0) {
        hash = (37 * hash) + IMAGE_URLS_FIELD_NUMBER;
        hash = (53 * hash) + getImageUrlsList().hashCode();
      }
      hash = (37 * hash) + PLACE_FIELD_NUMBER;
      hash = (53 * hash) + getPlace().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + category_;
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code warmup.service.SaveRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:warmup.service.SaveRequest)
        com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_SaveRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_SaveRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest.class, com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest.Builder.class);
      }

      // Construct using com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        description_ = "";

        imageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        place_ = "";

        category_ = 0;

        tag_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_SaveRequest_descriptor;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest getDefaultInstanceForType() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest build() {
        com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest buildPartial() {
        com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest result = new com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.description_ = description_;
        if (((bitField0_ & 0x00000001) != 0)) {
          imageUrls_ = imageUrls_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.imageUrls_ = imageUrls_;
        result.place_ = place_;
        result.category_ = category_;
        result.tag_ = tag_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest) {
          return mergeFrom((com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest other) {
        if (other == com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.imageUrls_.isEmpty()) {
          if (imageUrls_.isEmpty()) {
            imageUrls_ = other.imageUrls_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImageUrlsIsMutable();
            imageUrls_.addAll(other.imageUrls_);
          }
          onChanged();
        }
        if (!other.getPlace().isEmpty()) {
          place_ = other.place_;
          onChanged();
        }
        if (other.category_ != 0) {
          setCategoryValue(other.getCategoryValue());
        }
        if (!other.getTag().isEmpty()) {
          tag_ = other.tag_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList imageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImageUrlsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          imageUrls_ = new com.google.protobuf.LazyStringArrayList(imageUrls_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @return A list containing the imageUrls.
       */
      public com.google.protobuf.ProtocolStringList
          getImageUrlsList() {
        return imageUrls_.getUnmodifiableView();
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @return The count of imageUrls.
       */
      public int getImageUrlsCount() {
        return imageUrls_.size();
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @param index The index of the element to return.
       * @return The imageUrls at the given index.
       */
      public java.lang.String getImageUrls(int index) {
        return imageUrls_.get(index);
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the imageUrls at the given index.
       */
      public com.google.protobuf.ByteString
          getImageUrlsBytes(int index) {
        return imageUrls_.getByteString(index);
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @param index The index to set the value at.
       * @param value The imageUrls to set.
       * @return This builder for chaining.
       */
      public Builder setImageUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImageUrlsIsMutable();
        imageUrls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @param value The imageUrls to add.
       * @return This builder for chaining.
       */
      public Builder addImageUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImageUrlsIsMutable();
        imageUrls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @param values The imageUrls to add.
       * @return This builder for chaining.
       */
      public Builder addAllImageUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureImageUrlsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, imageUrls_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageUrls() {
        imageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string image_urls = 3;</code>
       * @param value The bytes of the imageUrls to add.
       * @return This builder for chaining.
       */
      public Builder addImageUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureImageUrlsIsMutable();
        imageUrls_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object place_ = "";
      /**
       * <code>string place = 4;</code>
       * @return The place.
       */
      public java.lang.String getPlace() {
        java.lang.Object ref = place_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          place_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string place = 4;</code>
       * @return The bytes for place.
       */
      public com.google.protobuf.ByteString
          getPlaceBytes() {
        java.lang.Object ref = place_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          place_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string place = 4;</code>
       * @param value The place to set.
       * @return This builder for chaining.
       */
      public Builder setPlace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        place_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string place = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlace() {
        
        place_ = getDefaultInstance().getPlace();
        onChanged();
        return this;
      }
      /**
       * <code>string place = 4;</code>
       * @param value The bytes for place to set.
       * @return This builder for chaining.
       */
      public Builder setPlaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        place_ = value;
        onChanged();
        return this;
      }

      private int category_ = 0;
      /**
       * <code>.warmup.type.Categories category = 5;</code>
       * @return The enum numeric value on the wire for category.
       */
      public int getCategoryValue() {
        return category_;
      }
      /**
       * <code>.warmup.type.Categories category = 5;</code>
       * @param value The enum numeric value on the wire for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryValue(int value) {
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.warmup.type.Categories category = 5;</code>
       * @return The category.
       */
      public com.depromeet.warmup.grpc.type.CategoryType.Categories getCategory() {
        @SuppressWarnings("deprecation")
        com.depromeet.warmup.grpc.type.CategoryType.Categories result = com.depromeet.warmup.grpc.type.CategoryType.Categories.valueOf(category_);
        return result == null ? com.depromeet.warmup.grpc.type.CategoryType.Categories.UNRECOGNIZED : result;
      }
      /**
       * <code>.warmup.type.Categories category = 5;</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(com.depromeet.warmup.grpc.type.CategoryType.Categories value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        category_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.warmup.type.Categories category = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        
        category_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tag_ = "";
      /**
       * <code>string tag = 6;</code>
       * @return The tag.
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tag = 6;</code>
       * @return The bytes for tag.
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag = 6;</code>
       * @param value The tag to set.
       * @return This builder for chaining.
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTag() {
        
        tag_ = getDefaultInstance().getTag();
        onChanged();
        return this;
      }
      /**
       * <code>string tag = 6;</code>
       * @param value The bytes for tag to set.
       * @return This builder for chaining.
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tag_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:warmup.service.SaveRequest)
    }

    // @@protoc_insertion_point(class_scope:warmup.service.SaveRequest)
    private static final com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest();
    }

    public static com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SaveRequest>
        PARSER = new com.google.protobuf.AbstractParser<SaveRequest>() {
      @java.lang.Override
      public SaveRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SaveRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SaveRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.depromeet.warmup.grpc.service.ItemOuterClass.SaveRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FindAllRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:warmup.service.FindAllRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>int32 lastId = 2;</code>
     * @return The lastId.
     */
    int getLastId();
  }
  /**
   * Protobuf type {@code warmup.service.FindAllRequest}
   */
  public  static final class FindAllRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:warmup.service.FindAllRequest)
      FindAllRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindAllRequest.newBuilder() to construct.
    private FindAllRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindAllRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FindAllRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindAllRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              size_ = input.readInt32();
              break;
            }
            case 16: {

              lastId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindAllRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindAllRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest.class, com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest.Builder.class);
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    public int getSize() {
      return size_;
    }

    public static final int LASTID_FIELD_NUMBER = 2;
    private int lastId_;
    /**
     * <code>int32 lastId = 2;</code>
     * @return The lastId.
     */
    public int getLastId() {
      return lastId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (size_ != 0) {
        output.writeInt32(1, size_);
      }
      if (lastId_ != 0) {
        output.writeInt32(2, lastId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      if (lastId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lastId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest)) {
        return super.equals(obj);
      }
      com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest other = (com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest) obj;

      if (getSize()
          != other.getSize()) return false;
      if (getLastId()
          != other.getLastId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (37 * hash) + LASTID_FIELD_NUMBER;
      hash = (53 * hash) + getLastId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code warmup.service.FindAllRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:warmup.service.FindAllRequest)
        com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindAllRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindAllRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest.class, com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest.Builder.class);
      }

      // Construct using com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        size_ = 0;

        lastId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindAllRequest_descriptor;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest getDefaultInstanceForType() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest build() {
        com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest buildPartial() {
        com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest result = new com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest(this);
        result.size_ = size_;
        result.lastId_ = lastId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest) {
          return mergeFrom((com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest other) {
        if (other == com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest.getDefaultInstance()) return this;
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (other.getLastId() != 0) {
          setLastId(other.getLastId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int size_ ;
      /**
       * <code>int32 size = 1;</code>
       * @return The size.
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private int lastId_ ;
      /**
       * <code>int32 lastId = 2;</code>
       * @return The lastId.
       */
      public int getLastId() {
        return lastId_;
      }
      /**
       * <code>int32 lastId = 2;</code>
       * @param value The lastId to set.
       * @return This builder for chaining.
       */
      public Builder setLastId(int value) {
        
        lastId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 lastId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastId() {
        
        lastId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:warmup.service.FindAllRequest)
    }

    // @@protoc_insertion_point(class_scope:warmup.service.FindAllRequest)
    private static final com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest();
    }

    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindAllRequest>
        PARSER = new com.google.protobuf.AbstractParser<FindAllRequest>() {
      @java.lang.Override
      public FindAllRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindAllRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindAllRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindAllRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.depromeet.warmup.grpc.service.ItemOuterClass.FindAllRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FindByIdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:warmup.service.FindByIdRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code warmup.service.FindByIdRequest}
   */
  public  static final class FindByIdRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:warmup.service.FindByIdRequest)
      FindByIdRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindByIdRequest.newBuilder() to construct.
    private FindByIdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindByIdRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FindByIdRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindByIdRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindByIdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindByIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest.class, com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest)) {
        return super.equals(obj);
      }
      com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest other = (com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code warmup.service.FindByIdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:warmup.service.FindByIdRequest)
        com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindByIdRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindByIdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest.class, com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest.Builder.class);
      }

      // Construct using com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.internal_static_warmup_service_FindByIdRequest_descriptor;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest getDefaultInstanceForType() {
        return com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest build() {
        com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest buildPartial() {
        com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest result = new com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest) {
          return mergeFrom((com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest other) {
        if (other == com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:warmup.service.FindByIdRequest)
    }

    // @@protoc_insertion_point(class_scope:warmup.service.FindByIdRequest)
    private static final com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest();
    }

    public static com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindByIdRequest>
        PARSER = new com.google.protobuf.AbstractParser<FindByIdRequest>() {
      @java.lang.Override
      public FindByIdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindByIdRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindByIdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindByIdRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.depromeet.warmup.grpc.service.ItemOuterClass.FindByIdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_warmup_service_SaveRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_warmup_service_SaveRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_warmup_service_FindAllRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_warmup_service_FindAllRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_warmup_service_FindByIdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_warmup_service_FindByIdRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nItem.proto\022\016warmup.service\032\021entity/ite" +
      "m.proto\032\030type/category_type.proto\"\213\001\n\013Sa" +
      "veRequest\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002" +
      " \001(\t\022\022\n\nimage_urls\030\003 \003(\t\022\r\n\005place\030\004 \001(\t\022" +
      ")\n\010category\030\005 \001(\0162\027.warmup.type.Categori" +
      "es\022\013\n\003tag\030\006 \001(\t\".\n\016FindAllRequest\022\014\n\004siz" +
      "e\030\001 \001(\005\022\016\n\006lastId\030\002 \001(\005\"\035\n\017FindByIdReque" +
      "st\022\n\n\002id\030\001 \001(\0032\304\001\n\004Item\0228\n\004Save\022\033.warmup" +
      ".service.SaveRequest\032\023.warmup.entity.Ite" +
      "m\022@\n\007FindAll\022\036.warmup.service.FindAllReq" +
      "uest\032\023.warmup.entity.Item0\001\022@\n\010FindById\022" +
      "\037.warmup.service.FindByIdRequest\032\023.warmu" +
      "p.entity.ItemB#\n!com.depromeet.warmup.gr" +
      "pc.serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.depromeet.warmup.grpc.entity.ItemOuterClass.getDescriptor(),
          com.depromeet.warmup.grpc.type.CategoryType.getDescriptor(),
        });
    internal_static_warmup_service_SaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_warmup_service_SaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_warmup_service_SaveRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "ImageUrls", "Place", "Category", "Tag", });
    internal_static_warmup_service_FindAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_warmup_service_FindAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_warmup_service_FindAllRequest_descriptor,
        new java.lang.String[] { "Size", "LastId", });
    internal_static_warmup_service_FindByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_warmup_service_FindByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_warmup_service_FindByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    com.depromeet.warmup.grpc.entity.ItemOuterClass.getDescriptor();
    com.depromeet.warmup.grpc.type.CategoryType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
