language: java
sudo: false

jdk:
  - openjdk12

before_script:
  - chmod +x gradlew
  - git submodule update
  - ./gradlew generateProto

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)