spring:
  profiles: local
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /team4
      settings:
        web-allow-others: true

#  datasource:
#    url: jdbc:h2:~/team4-console
#    driver-class-name: org.h2.Driver
#    username: team4
#    password: team4
#



