// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity/item.proto

package com.depromeet.warmup.grpc.entity;

public final class ItemOuterClass {
  private ItemOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:warmup.entity.Item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 11;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>.warmup.type.BarterStatus barter_status = 3;</code>
     * @return The enum numeric value on the wire for barterStatus.
     */
    int getBarterStatusValue();
    /**
     * <code>.warmup.type.BarterStatus barter_status = 3;</code>
     * @return The barterStatus.
     */
    com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus getBarterStatus();

    /**
     * <code>repeated string images = 4;</code>
     * @return A list containing the images.
     */
    java.util.List<java.lang.String>
        getImagesList();
    /**
     * <code>repeated string images = 4;</code>
     * @return The count of images.
     */
    int getImagesCount();
    /**
     * <code>repeated string images = 4;</code>
     * @param index The index of the element to return.
     * @return The images at the given index.
     */
    java.lang.String getImages(int index);
    /**
     * <code>repeated string images = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the images at the given index.
     */
    com.google.protobuf.ByteString
        getImagesBytes(int index);

    /**
     * <code>string place = 5;</code>
     * @return The place.
     */
    java.lang.String getPlace();
    /**
     * <code>string place = 5;</code>
     * @return The bytes for place.
     */
    com.google.protobuf.ByteString
        getPlaceBytes();

    /**
     * <code>.warmup.type.Categories category = 6;</code>
     * @return The enum numeric value on the wire for category.
     */
    int getCategoryValue();
    /**
     * <code>.warmup.type.Categories category = 6;</code>
     * @return The category.
     */
    com.depromeet.warmup.grpc.type.CategoryType.Categories getCategory();

    /**
     * <code>string tag = 7;</code>
     * @return The tag.
     */
    java.lang.String getTag();
    /**
     * <code>string tag = 7;</code>
     * @return The bytes for tag.
     */
    com.google.protobuf.ByteString
        getTagBytes();

    /**
     * <code>.warmup.entity.User owner = 8;</code>
     * @return Whether the owner field is set.
     */
    boolean hasOwner();
    /**
     * <code>.warmup.entity.User owner = 8;</code>
     * @return The owner.
     */
    com.depromeet.warmup.grpc.entity.UserOuterClass.User getOwner();
    /**
     * <code>.warmup.entity.User owner = 8;</code>
     */
    com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder getOwnerOrBuilder();

    /**
     * <code>int64 created_date = 9;</code>
     * @return The createdDate.
     */
    long getCreatedDate();

    /**
     * <code>int64 last_modified_date = 10;</code>
     * @return The lastModifiedDate.
     */
    long getLastModifiedDate();
  }
  /**
   * <pre>
   * 아이템(물물교환 대상) 정보
   * </pre>
   *
   * Protobuf type {@code warmup.entity.Item}
   */
  public  static final class Item extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:warmup.entity.Item)
      ItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Item() {
      name_ = "";
      description_ = "";
      barterStatus_ = 0;
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      place_ = "";
      category_ = 0;
      tag_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Item();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              barterStatus_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                images_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              images_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              place_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              category_ = rawValue;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              tag_ = s;
              break;
            }
            case 66: {
              com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder subBuilder = null;
              if (owner_ != null) {
                subBuilder = owner_.toBuilder();
              }
              owner_ = input.readMessage(com.depromeet.warmup.grpc.entity.UserOuterClass.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(owner_);
                owner_ = subBuilder.buildPartial();
              }

              break;
            }
            case 72: {

              createdDate_ = input.readInt64();
              break;
            }
            case 80: {

              lastModifiedDate_ = input.readInt64();
              break;
            }
            case 88: {

              id_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          images_ = images_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.class, com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 11;
    private long id_;
    /**
     * <code>int64 id = 11;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BARTER_STATUS_FIELD_NUMBER = 3;
    private int barterStatus_;
    /**
     * <code>.warmup.type.BarterStatus barter_status = 3;</code>
     * @return The enum numeric value on the wire for barterStatus.
     */
    public int getBarterStatusValue() {
      return barterStatus_;
    }
    /**
     * <code>.warmup.type.BarterStatus barter_status = 3;</code>
     * @return The barterStatus.
     */
    public com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus getBarterStatus() {
      @SuppressWarnings("deprecation")
      com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus result = com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.valueOf(barterStatus_);
      return result == null ? com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.UNRECOGNIZED : result;
    }

    public static final int IMAGES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList images_;
    /**
     * <code>repeated string images = 4;</code>
     * @return A list containing the images.
     */
    public com.google.protobuf.ProtocolStringList
        getImagesList() {
      return images_;
    }
    /**
     * <code>repeated string images = 4;</code>
     * @return The count of images.
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated string images = 4;</code>
     * @param index The index of the element to return.
     * @return The images at the given index.
     */
    public java.lang.String getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated string images = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the images at the given index.
     */
    public com.google.protobuf.ByteString
        getImagesBytes(int index) {
      return images_.getByteString(index);
    }

    public static final int PLACE_FIELD_NUMBER = 5;
    private volatile java.lang.Object place_;
    /**
     * <code>string place = 5;</code>
     * @return The place.
     */
    public java.lang.String getPlace() {
      java.lang.Object ref = place_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        place_ = s;
        return s;
      }
    }
    /**
     * <code>string place = 5;</code>
     * @return The bytes for place.
     */
    public com.google.protobuf.ByteString
        getPlaceBytes() {
      java.lang.Object ref = place_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        place_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 6;
    private int category_;
    /**
     * <code>.warmup.type.Categories category = 6;</code>
     * @return The enum numeric value on the wire for category.
     */
    public int getCategoryValue() {
      return category_;
    }
    /**
     * <code>.warmup.type.Categories category = 6;</code>
     * @return The category.
     */
    public com.depromeet.warmup.grpc.type.CategoryType.Categories getCategory() {
      @SuppressWarnings("deprecation")
      com.depromeet.warmup.grpc.type.CategoryType.Categories result = com.depromeet.warmup.grpc.type.CategoryType.Categories.valueOf(category_);
      return result == null ? com.depromeet.warmup.grpc.type.CategoryType.Categories.UNRECOGNIZED : result;
    }

    public static final int TAG_FIELD_NUMBER = 7;
    private volatile java.lang.Object tag_;
    /**
     * <code>string tag = 7;</code>
     * @return The tag.
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      }
    }
    /**
     * <code>string tag = 7;</code>
     * @return The bytes for tag.
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNER_FIELD_NUMBER = 8;
    private com.depromeet.warmup.grpc.entity.UserOuterClass.User owner_;
    /**
     * <code>.warmup.entity.User owner = 8;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return owner_ != null;
    }
    /**
     * <code>.warmup.entity.User owner = 8;</code>
     * @return The owner.
     */
    public com.depromeet.warmup.grpc.entity.UserOuterClass.User getOwner() {
      return owner_ == null ? com.depromeet.warmup.grpc.entity.UserOuterClass.User.getDefaultInstance() : owner_;
    }
    /**
     * <code>.warmup.entity.User owner = 8;</code>
     */
    public com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder getOwnerOrBuilder() {
      return getOwner();
    }

    public static final int CREATED_DATE_FIELD_NUMBER = 9;
    private long createdDate_;
    /**
     * <code>int64 created_date = 9;</code>
     * @return The createdDate.
     */
    public long getCreatedDate() {
      return createdDate_;
    }

    public static final int LAST_MODIFIED_DATE_FIELD_NUMBER = 10;
    private long lastModifiedDate_;
    /**
     * <code>int64 last_modified_date = 10;</code>
     * @return The lastModifiedDate.
     */
    public long getLastModifiedDate() {
      return lastModifiedDate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      if (barterStatus_ != com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.WAIT.getNumber()) {
        output.writeEnum(3, barterStatus_);
      }
      for (int i = 0; i < images_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, images_.getRaw(i));
      }
      if (!getPlaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, place_);
      }
      if (category_ != com.depromeet.warmup.grpc.type.CategoryType.Categories.FOOD.getNumber()) {
        output.writeEnum(6, category_);
      }
      if (!getTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, tag_);
      }
      if (owner_ != null) {
        output.writeMessage(8, getOwner());
      }
      if (createdDate_ != 0L) {
        output.writeInt64(9, createdDate_);
      }
      if (lastModifiedDate_ != 0L) {
        output.writeInt64(10, lastModifiedDate_);
      }
      if (id_ != 0L) {
        output.writeInt64(11, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      if (barterStatus_ != com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.WAIT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, barterStatus_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < images_.size(); i++) {
          dataSize += computeStringSizeNoTag(images_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getImagesList().size();
      }
      if (!getPlaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, place_);
      }
      if (category_ != com.depromeet.warmup.grpc.type.CategoryType.Categories.FOOD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, category_);
      }
      if (!getTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, tag_);
      }
      if (owner_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getOwner());
      }
      if (createdDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, createdDate_);
      }
      if (lastModifiedDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, lastModifiedDate_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.depromeet.warmup.grpc.entity.ItemOuterClass.Item)) {
        return super.equals(obj);
      }
      com.depromeet.warmup.grpc.entity.ItemOuterClass.Item other = (com.depromeet.warmup.grpc.entity.ItemOuterClass.Item) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (barterStatus_ != other.barterStatus_) return false;
      if (!getImagesList()
          .equals(other.getImagesList())) return false;
      if (!getPlace()
          .equals(other.getPlace())) return false;
      if (category_ != other.category_) return false;
      if (!getTag()
          .equals(other.getTag())) return false;
      if (hasOwner() != other.hasOwner()) return false;
      if (hasOwner()) {
        if (!getOwner()
            .equals(other.getOwner())) return false;
      }
      if (getCreatedDate()
          != other.getCreatedDate()) return false;
      if (getLastModifiedDate()
          != other.getLastModifiedDate()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + BARTER_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + barterStatus_;
      if (getImagesCount() > 0) {
        hash = (37 * hash) + IMAGES_FIELD_NUMBER;
        hash = (53 * hash) + getImagesList().hashCode();
      }
      hash = (37 * hash) + PLACE_FIELD_NUMBER;
      hash = (53 * hash) + getPlace().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + category_;
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag().hashCode();
      if (hasOwner()) {
        hash = (37 * hash) + OWNER_FIELD_NUMBER;
        hash = (53 * hash) + getOwner().hashCode();
      }
      hash = (37 * hash) + CREATED_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedDate());
      hash = (37 * hash) + LAST_MODIFIED_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastModifiedDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.depromeet.warmup.grpc.entity.ItemOuterClass.Item prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 아이템(물물교환 대상) 정보
     * </pre>
     *
     * Protobuf type {@code warmup.entity.Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:warmup.entity.Item)
        com.depromeet.warmup.grpc.entity.ItemOuterClass.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.class, com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.Builder.class);
      }

      // Construct using com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        description_ = "";

        barterStatus_ = 0;

        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        place_ = "";

        category_ = 0;

        tag_ = "";

        if (ownerBuilder_ == null) {
          owner_ = null;
        } else {
          owner_ = null;
          ownerBuilder_ = null;
        }
        createdDate_ = 0L;

        lastModifiedDate_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_descriptor;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.entity.ItemOuterClass.Item getDefaultInstanceForType() {
        return com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.getDefaultInstance();
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.entity.ItemOuterClass.Item build() {
        com.depromeet.warmup.grpc.entity.ItemOuterClass.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.entity.ItemOuterClass.Item buildPartial() {
        com.depromeet.warmup.grpc.entity.ItemOuterClass.Item result = new com.depromeet.warmup.grpc.entity.ItemOuterClass.Item(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.description_ = description_;
        result.barterStatus_ = barterStatus_;
        if (((bitField0_ & 0x00000001) != 0)) {
          images_ = images_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.images_ = images_;
        result.place_ = place_;
        result.category_ = category_;
        result.tag_ = tag_;
        if (ownerBuilder_ == null) {
          result.owner_ = owner_;
        } else {
          result.owner_ = ownerBuilder_.build();
        }
        result.createdDate_ = createdDate_;
        result.lastModifiedDate_ = lastModifiedDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.depromeet.warmup.grpc.entity.ItemOuterClass.Item) {
          return mergeFrom((com.depromeet.warmup.grpc.entity.ItemOuterClass.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.depromeet.warmup.grpc.entity.ItemOuterClass.Item other) {
        if (other == com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.barterStatus_ != 0) {
          setBarterStatusValue(other.getBarterStatusValue());
        }
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
        if (!other.getPlace().isEmpty()) {
          place_ = other.place_;
          onChanged();
        }
        if (other.category_ != 0) {
          setCategoryValue(other.getCategoryValue());
        }
        if (!other.getTag().isEmpty()) {
          tag_ = other.tag_;
          onChanged();
        }
        if (other.hasOwner()) {
          mergeOwner(other.getOwner());
        }
        if (other.getCreatedDate() != 0L) {
          setCreatedDate(other.getCreatedDate());
        }
        if (other.getLastModifiedDate() != 0L) {
          setLastModifiedDate(other.getLastModifiedDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.depromeet.warmup.grpc.entity.ItemOuterClass.Item) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 11;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 11;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int barterStatus_ = 0;
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @return The enum numeric value on the wire for barterStatus.
       */
      public int getBarterStatusValue() {
        return barterStatus_;
      }
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @param value The enum numeric value on the wire for barterStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBarterStatusValue(int value) {
        barterStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @return The barterStatus.
       */
      public com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus getBarterStatus() {
        @SuppressWarnings("deprecation")
        com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus result = com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.valueOf(barterStatus_);
        return result == null ? com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @param value The barterStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBarterStatus(com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        barterStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBarterStatus() {
        
        barterStatus_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          images_ = new com.google.protobuf.LazyStringArrayList(images_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string images = 4;</code>
       * @return A list containing the images.
       */
      public com.google.protobuf.ProtocolStringList
          getImagesList() {
        return images_.getUnmodifiableView();
      }
      /**
       * <code>repeated string images = 4;</code>
       * @return The count of images.
       */
      public int getImagesCount() {
        return images_.size();
      }
      /**
       * <code>repeated string images = 4;</code>
       * @param index The index of the element to return.
       * @return The images at the given index.
       */
      public java.lang.String getImages(int index) {
        return images_.get(index);
      }
      /**
       * <code>repeated string images = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the images at the given index.
       */
      public com.google.protobuf.ByteString
          getImagesBytes(int index) {
        return images_.getByteString(index);
      }
      /**
       * <code>repeated string images = 4;</code>
       * @param index The index to set the value at.
       * @param value The images to set.
       * @return This builder for chaining.
       */
      public Builder setImages(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 4;</code>
       * @param value The images to add.
       * @return This builder for chaining.
       */
      public Builder addImages(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 4;</code>
       * @param values The images to add.
       * @return This builder for chaining.
       */
      public Builder addAllImages(
          java.lang.Iterable<java.lang.String> values) {
        ensureImagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, images_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearImages() {
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 4;</code>
       * @param value The bytes of the images to add.
       * @return This builder for chaining.
       */
      public Builder addImagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object place_ = "";
      /**
       * <code>string place = 5;</code>
       * @return The place.
       */
      public java.lang.String getPlace() {
        java.lang.Object ref = place_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          place_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string place = 5;</code>
       * @return The bytes for place.
       */
      public com.google.protobuf.ByteString
          getPlaceBytes() {
        java.lang.Object ref = place_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          place_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string place = 5;</code>
       * @param value The place to set.
       * @return This builder for chaining.
       */
      public Builder setPlace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        place_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string place = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlace() {
        
        place_ = getDefaultInstance().getPlace();
        onChanged();
        return this;
      }
      /**
       * <code>string place = 5;</code>
       * @param value The bytes for place to set.
       * @return This builder for chaining.
       */
      public Builder setPlaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        place_ = value;
        onChanged();
        return this;
      }

      private int category_ = 0;
      /**
       * <code>.warmup.type.Categories category = 6;</code>
       * @return The enum numeric value on the wire for category.
       */
      public int getCategoryValue() {
        return category_;
      }
      /**
       * <code>.warmup.type.Categories category = 6;</code>
       * @param value The enum numeric value on the wire for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryValue(int value) {
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.warmup.type.Categories category = 6;</code>
       * @return The category.
       */
      public com.depromeet.warmup.grpc.type.CategoryType.Categories getCategory() {
        @SuppressWarnings("deprecation")
        com.depromeet.warmup.grpc.type.CategoryType.Categories result = com.depromeet.warmup.grpc.type.CategoryType.Categories.valueOf(category_);
        return result == null ? com.depromeet.warmup.grpc.type.CategoryType.Categories.UNRECOGNIZED : result;
      }
      /**
       * <code>.warmup.type.Categories category = 6;</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(com.depromeet.warmup.grpc.type.CategoryType.Categories value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        category_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.warmup.type.Categories category = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        
        category_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tag_ = "";
      /**
       * <code>string tag = 7;</code>
       * @return The tag.
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tag = 7;</code>
       * @return The bytes for tag.
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag = 7;</code>
       * @param value The tag to set.
       * @return This builder for chaining.
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTag() {
        
        tag_ = getDefaultInstance().getTag();
        onChanged();
        return this;
      }
      /**
       * <code>string tag = 7;</code>
       * @param value The bytes for tag to set.
       * @return This builder for chaining.
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tag_ = value;
        onChanged();
        return this;
      }

      private com.depromeet.warmup.grpc.entity.UserOuterClass.User owner_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.depromeet.warmup.grpc.entity.UserOuterClass.User, com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder, com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder> ownerBuilder_;
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       * @return Whether the owner field is set.
       */
      public boolean hasOwner() {
        return ownerBuilder_ != null || owner_ != null;
      }
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       * @return The owner.
       */
      public com.depromeet.warmup.grpc.entity.UserOuterClass.User getOwner() {
        if (ownerBuilder_ == null) {
          return owner_ == null ? com.depromeet.warmup.grpc.entity.UserOuterClass.User.getDefaultInstance() : owner_;
        } else {
          return ownerBuilder_.getMessage();
        }
      }
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       */
      public Builder setOwner(com.depromeet.warmup.grpc.entity.UserOuterClass.User value) {
        if (ownerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          owner_ = value;
          onChanged();
        } else {
          ownerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       */
      public Builder setOwner(
          com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder builderForValue) {
        if (ownerBuilder_ == null) {
          owner_ = builderForValue.build();
          onChanged();
        } else {
          ownerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       */
      public Builder mergeOwner(com.depromeet.warmup.grpc.entity.UserOuterClass.User value) {
        if (ownerBuilder_ == null) {
          if (owner_ != null) {
            owner_ =
              com.depromeet.warmup.grpc.entity.UserOuterClass.User.newBuilder(owner_).mergeFrom(value).buildPartial();
          } else {
            owner_ = value;
          }
          onChanged();
        } else {
          ownerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       */
      public Builder clearOwner() {
        if (ownerBuilder_ == null) {
          owner_ = null;
          onChanged();
        } else {
          owner_ = null;
          ownerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       */
      public com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder getOwnerBuilder() {
        
        onChanged();
        return getOwnerFieldBuilder().getBuilder();
      }
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       */
      public com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder getOwnerOrBuilder() {
        if (ownerBuilder_ != null) {
          return ownerBuilder_.getMessageOrBuilder();
        } else {
          return owner_ == null ?
              com.depromeet.warmup.grpc.entity.UserOuterClass.User.getDefaultInstance() : owner_;
        }
      }
      /**
       * <code>.warmup.entity.User owner = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.depromeet.warmup.grpc.entity.UserOuterClass.User, com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder, com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder> 
          getOwnerFieldBuilder() {
        if (ownerBuilder_ == null) {
          ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.depromeet.warmup.grpc.entity.UserOuterClass.User, com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder, com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder>(
                  getOwner(),
                  getParentForChildren(),
                  isClean());
          owner_ = null;
        }
        return ownerBuilder_;
      }

      private long createdDate_ ;
      /**
       * <code>int64 created_date = 9;</code>
       * @return The createdDate.
       */
      public long getCreatedDate() {
        return createdDate_;
      }
      /**
       * <code>int64 created_date = 9;</code>
       * @param value The createdDate to set.
       * @return This builder for chaining.
       */
      public Builder setCreatedDate(long value) {
        
        createdDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 created_date = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreatedDate() {
        
        createdDate_ = 0L;
        onChanged();
        return this;
      }

      private long lastModifiedDate_ ;
      /**
       * <code>int64 last_modified_date = 10;</code>
       * @return The lastModifiedDate.
       */
      public long getLastModifiedDate() {
        return lastModifiedDate_;
      }
      /**
       * <code>int64 last_modified_date = 10;</code>
       * @param value The lastModifiedDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastModifiedDate(long value) {
        
        lastModifiedDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_modified_date = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastModifiedDate() {
        
        lastModifiedDate_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:warmup.entity.Item)
    }

    // @@protoc_insertion_point(class_scope:warmup.entity.Item)
    private static final com.depromeet.warmup.grpc.entity.ItemOuterClass.Item DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.depromeet.warmup.grpc.entity.ItemOuterClass.Item();
    }

    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Item>
        PARSER = new com.google.protobuf.AbstractParser<Item>() {
      @java.lang.Override
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Item(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Item> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.depromeet.warmup.grpc.entity.ItemOuterClass.Item getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_warmup_entity_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_warmup_entity_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021entity/item.proto\022\rwarmup.entity\032\022enti" +
      "ty/image.proto\032\021entity/user.proto\032\030type/" +
      "barter_status.proto\032\030type/category_type." +
      "proto\"\224\002\n\004Item\022\n\n\002id\030\013 \001(\003\022\014\n\004name\030\001 \001(\t" +
      "\022\023\n\013description\030\002 \001(\t\0220\n\rbarter_status\030\003" +
      " \001(\0162\031.warmup.type.BarterStatus\022\016\n\006image" +
      "s\030\004 \003(\t\022\r\n\005place\030\005 \001(\t\022)\n\010category\030\006 \001(\016" +
      "2\027.warmup.type.Categories\022\013\n\003tag\030\007 \001(\t\022\"" +
      "\n\005owner\030\010 \001(\0132\023.warmup.entity.User\022\024\n\014cr" +
      "eated_date\030\t \001(\003\022\032\n\022last_modified_date\030\n" +
      " \001(\003B\"\n com.depromeet.warmup.grpc.entity" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.depromeet.warmup.grpc.entity.ImageOuterClass.getDescriptor(),
          com.depromeet.warmup.grpc.entity.UserOuterClass.getDescriptor(),
          com.depromeet.warmup.grpc.type.BarterStatusOuterClass.getDescriptor(),
          com.depromeet.warmup.grpc.type.CategoryType.getDescriptor(),
        });
    internal_static_warmup_entity_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_warmup_entity_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_warmup_entity_Item_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "BarterStatus", "Images", "Place", "Category", "Tag", "Owner", "CreatedDate", "LastModifiedDate", });
    com.depromeet.warmup.grpc.entity.ImageOuterClass.getDescriptor();
    com.depromeet.warmup.grpc.entity.UserOuterClass.getDescriptor();
    com.depromeet.warmup.grpc.type.BarterStatusOuterClass.getDescriptor();
    com.depromeet.warmup.grpc.type.CategoryType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
