// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity/item.proto

package com.depromeet.warmup.grpc.entity;

public final class ItemOuterClass {
  private ItemOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:warmup.entity.Item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>.warmup.type.BarterStatus barter_status = 3;</code>
     * @return The enum numeric value on the wire for barterStatus.
     */
    int getBarterStatusValue();
    /**
     * <code>.warmup.type.BarterStatus barter_status = 3;</code>
     * @return The barterStatus.
     */
    com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus getBarterStatus();

    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    java.util.List<com.depromeet.warmup.grpc.entity.ImageOuterClass.Image> 
        getImagesList();
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    com.depromeet.warmup.grpc.entity.ImageOuterClass.Image getImages(int index);
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    int getImagesCount();
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    java.util.List<? extends com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder> 
        getImagesOrBuilderList();
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder getImagesOrBuilder(
        int index);

    /**
     * <code>.warmup.entity.User owner = 5;</code>
     * @return Whether the owner field is set.
     */
    boolean hasOwner();
    /**
     * <code>.warmup.entity.User owner = 5;</code>
     * @return The owner.
     */
    com.depromeet.warmup.grpc.entity.UserOuterClass.User getOwner();
    /**
     * <code>.warmup.entity.User owner = 5;</code>
     */
    com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder getOwnerOrBuilder();

    /**
     * <code>int64 created_date = 6;</code>
     * @return The createdDate.
     */
    long getCreatedDate();

    /**
     * <code>int64 last_modified_date = 7;</code>
     * @return The lastModifiedDate.
     */
    long getLastModifiedDate();
  }
  /**
   * <pre>
   * 아이템(물물교환 대상) 정보
   * </pre>
   *
   * Protobuf type {@code warmup.entity.Item}
   */
  public  static final class Item extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:warmup.entity.Item)
      ItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Item() {
      name_ = "";
      description_ = "";
      barterStatus_ = 0;
      images_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Item();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              barterStatus_ = rawValue;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                images_ = new java.util.ArrayList<com.depromeet.warmup.grpc.entity.ImageOuterClass.Image>();
                mutable_bitField0_ |= 0x00000001;
              }
              images_.add(
                  input.readMessage(com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.parser(), extensionRegistry));
              break;
            }
            case 42: {
              com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder subBuilder = null;
              if (owner_ != null) {
                subBuilder = owner_.toBuilder();
              }
              owner_ = input.readMessage(com.depromeet.warmup.grpc.entity.UserOuterClass.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(owner_);
                owner_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {

              createdDate_ = input.readInt64();
              break;
            }
            case 56: {

              lastModifiedDate_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          images_ = java.util.Collections.unmodifiableList(images_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.class, com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BARTER_STATUS_FIELD_NUMBER = 3;
    private int barterStatus_;
    /**
     * <code>.warmup.type.BarterStatus barter_status = 3;</code>
     * @return The enum numeric value on the wire for barterStatus.
     */
    public int getBarterStatusValue() {
      return barterStatus_;
    }
    /**
     * <code>.warmup.type.BarterStatus barter_status = 3;</code>
     * @return The barterStatus.
     */
    public com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus getBarterStatus() {
      @SuppressWarnings("deprecation")
      com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus result = com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.valueOf(barterStatus_);
      return result == null ? com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.UNRECOGNIZED : result;
    }

    public static final int IMAGES_FIELD_NUMBER = 4;
    private java.util.List<com.depromeet.warmup.grpc.entity.ImageOuterClass.Image> images_;
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    public java.util.List<com.depromeet.warmup.grpc.entity.ImageOuterClass.Image> getImagesList() {
      return images_;
    }
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    public java.util.List<? extends com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder> 
        getImagesOrBuilderList() {
      return images_;
    }
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    public com.depromeet.warmup.grpc.entity.ImageOuterClass.Image getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated .warmup.entity.Image images = 4;</code>
     */
    public com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder getImagesOrBuilder(
        int index) {
      return images_.get(index);
    }

    public static final int OWNER_FIELD_NUMBER = 5;
    private com.depromeet.warmup.grpc.entity.UserOuterClass.User owner_;
    /**
     * <code>.warmup.entity.User owner = 5;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return owner_ != null;
    }
    /**
     * <code>.warmup.entity.User owner = 5;</code>
     * @return The owner.
     */
    public com.depromeet.warmup.grpc.entity.UserOuterClass.User getOwner() {
      return owner_ == null ? com.depromeet.warmup.grpc.entity.UserOuterClass.User.getDefaultInstance() : owner_;
    }
    /**
     * <code>.warmup.entity.User owner = 5;</code>
     */
    public com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder getOwnerOrBuilder() {
      return getOwner();
    }

    public static final int CREATED_DATE_FIELD_NUMBER = 6;
    private long createdDate_;
    /**
     * <code>int64 created_date = 6;</code>
     * @return The createdDate.
     */
    public long getCreatedDate() {
      return createdDate_;
    }

    public static final int LAST_MODIFIED_DATE_FIELD_NUMBER = 7;
    private long lastModifiedDate_;
    /**
     * <code>int64 last_modified_date = 7;</code>
     * @return The lastModifiedDate.
     */
    public long getLastModifiedDate() {
      return lastModifiedDate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      if (barterStatus_ != com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.WAIT.getNumber()) {
        output.writeEnum(3, barterStatus_);
      }
      for (int i = 0; i < images_.size(); i++) {
        output.writeMessage(4, images_.get(i));
      }
      if (owner_ != null) {
        output.writeMessage(5, getOwner());
      }
      if (createdDate_ != 0L) {
        output.writeInt64(6, createdDate_);
      }
      if (lastModifiedDate_ != 0L) {
        output.writeInt64(7, lastModifiedDate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      if (barterStatus_ != com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.WAIT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, barterStatus_);
      }
      for (int i = 0; i < images_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, images_.get(i));
      }
      if (owner_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getOwner());
      }
      if (createdDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createdDate_);
      }
      if (lastModifiedDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, lastModifiedDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.depromeet.warmup.grpc.entity.ItemOuterClass.Item)) {
        return super.equals(obj);
      }
      com.depromeet.warmup.grpc.entity.ItemOuterClass.Item other = (com.depromeet.warmup.grpc.entity.ItemOuterClass.Item) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (barterStatus_ != other.barterStatus_) return false;
      if (!getImagesList()
          .equals(other.getImagesList())) return false;
      if (hasOwner() != other.hasOwner()) return false;
      if (hasOwner()) {
        if (!getOwner()
            .equals(other.getOwner())) return false;
      }
      if (getCreatedDate()
          != other.getCreatedDate()) return false;
      if (getLastModifiedDate()
          != other.getLastModifiedDate()) return false;
        return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + BARTER_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + barterStatus_;
      if (getImagesCount() > 0) {
        hash = (37 * hash) + IMAGES_FIELD_NUMBER;
        hash = (53 * hash) + getImagesList().hashCode();
      }
      if (hasOwner()) {
        hash = (37 * hash) + OWNER_FIELD_NUMBER;
        hash = (53 * hash) + getOwner().hashCode();
      }
      hash = (37 * hash) + CREATED_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedDate());
      hash = (37 * hash) + LAST_MODIFIED_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastModifiedDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.depromeet.warmup.grpc.entity.ItemOuterClass.Item prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 아이템(물물교환 대상) 정보
     * </pre>
     *
     * Protobuf type {@code warmup.entity.Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:warmup.entity.Item)
        com.depromeet.warmup.grpc.entity.ItemOuterClass.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.class, com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.Builder.class);
      }

      // Construct using com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getImagesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        description_ = "";

        barterStatus_ = 0;

        if (imagesBuilder_ == null) {
          images_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          imagesBuilder_.clear();
        }
        if (ownerBuilder_ == null) {
          owner_ = null;
        } else {
          owner_ = null;
          ownerBuilder_ = null;
        }
        createdDate_ = 0L;

        lastModifiedDate_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.depromeet.warmup.grpc.entity.ItemOuterClass.internal_static_warmup_entity_Item_descriptor;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.entity.ItemOuterClass.Item getDefaultInstanceForType() {
        return com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.getDefaultInstance();
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.entity.ItemOuterClass.Item build() {
        com.depromeet.warmup.grpc.entity.ItemOuterClass.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.depromeet.warmup.grpc.entity.ItemOuterClass.Item buildPartial() {
        com.depromeet.warmup.grpc.entity.ItemOuterClass.Item result = new com.depromeet.warmup.grpc.entity.ItemOuterClass.Item(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.description_ = description_;
        result.barterStatus_ = barterStatus_;
        if (imagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            images_ = java.util.Collections.unmodifiableList(images_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.images_ = images_;
        } else {
          result.images_ = imagesBuilder_.build();
        }
        if (ownerBuilder_ == null) {
          result.owner_ = owner_;
        } else {
          result.owner_ = ownerBuilder_.build();
        }
        result.createdDate_ = createdDate_;
        result.lastModifiedDate_ = lastModifiedDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.depromeet.warmup.grpc.entity.ItemOuterClass.Item) {
          return mergeFrom((com.depromeet.warmup.grpc.entity.ItemOuterClass.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.depromeet.warmup.grpc.entity.ItemOuterClass.Item other) {
        if (other == com.depromeet.warmup.grpc.entity.ItemOuterClass.Item.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.barterStatus_ != 0) {
          setBarterStatusValue(other.getBarterStatusValue());
        }
        if (imagesBuilder_ == null) {
          if (!other.images_.isEmpty()) {
            if (images_.isEmpty()) {
              images_ = other.images_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureImagesIsMutable();
              images_.addAll(other.images_);
            }
            onChanged();
          }
        } else {
          if (!other.images_.isEmpty()) {
            if (imagesBuilder_.isEmpty()) {
              imagesBuilder_.dispose();
              imagesBuilder_ = null;
              images_ = other.images_;
              bitField0_ = (bitField0_ & ~0x00000001);
              imagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getImagesFieldBuilder() : null;
            } else {
              imagesBuilder_.addAllMessages(other.images_);
            }
          }
        }
        if (other.hasOwner()) {
          mergeOwner(other.getOwner());
        }
        if (other.getCreatedDate() != 0L) {
          setCreatedDate(other.getCreatedDate());
        }
        if (other.getLastModifiedDate() != 0L) {
          setLastModifiedDate(other.getLastModifiedDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.depromeet.warmup.grpc.entity.ItemOuterClass.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.depromeet.warmup.grpc.entity.ItemOuterClass.Item) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int barterStatus_ = 0;
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @return The enum numeric value on the wire for barterStatus.
       */
      public int getBarterStatusValue() {
        return barterStatus_;
      }
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @param value The enum numeric value on the wire for barterStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBarterStatusValue(int value) {
        barterStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @return The barterStatus.
       */
      public com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus getBarterStatus() {
        @SuppressWarnings("deprecation")
        com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus result = com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.valueOf(barterStatus_);
        return result == null ? com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @param value The barterStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBarterStatus(com.depromeet.warmup.grpc.type.BarterStatusOuterClass.BarterStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        barterStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.warmup.type.BarterStatus barter_status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBarterStatus() {
        
        barterStatus_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.depromeet.warmup.grpc.entity.ImageOuterClass.Image> images_ =
        java.util.Collections.emptyList();
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          images_ = new java.util.ArrayList<com.depromeet.warmup.grpc.entity.ImageOuterClass.Image>(images_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.depromeet.warmup.grpc.entity.ImageOuterClass.Image, com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder, com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder> imagesBuilder_;

      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public java.util.List<com.depromeet.warmup.grpc.entity.ImageOuterClass.Image> getImagesList() {
        if (imagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(images_);
        } else {
          return imagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public int getImagesCount() {
        if (imagesBuilder_ == null) {
          return images_.size();
        } else {
          return imagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public com.depromeet.warmup.grpc.entity.ImageOuterClass.Image getImages(int index) {
        if (imagesBuilder_ == null) {
          return images_.get(index);
        } else {
          return imagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder setImages(
          int index, com.depromeet.warmup.grpc.entity.ImageOuterClass.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.set(index, value);
          onChanged();
        } else {
          imagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder setImages(
          int index, com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.set(index, builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder addImages(com.depromeet.warmup.grpc.entity.ImageOuterClass.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.add(value);
          onChanged();
        } else {
          imagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder addImages(
          int index, com.depromeet.warmup.grpc.entity.ImageOuterClass.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.add(index, value);
          onChanged();
        } else {
          imagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder addImages(
          com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.add(builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder addImages(
          int index, com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.add(index, builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder addAllImages(
          java.lang.Iterable<? extends com.depromeet.warmup.grpc.entity.ImageOuterClass.Image> values) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, images_);
          onChanged();
        } else {
          imagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder clearImages() {
        if (imagesBuilder_ == null) {
          images_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          imagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public Builder removeImages(int index) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.remove(index);
          onChanged();
        } else {
          imagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder getImagesBuilder(
          int index) {
        return getImagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder getImagesOrBuilder(
          int index) {
        if (imagesBuilder_ == null) {
          return images_.get(index);  } else {
          return imagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public java.util.List<? extends com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder> 
           getImagesOrBuilderList() {
        if (imagesBuilder_ != null) {
          return imagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(images_);
        }
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder addImagesBuilder() {
        return getImagesFieldBuilder().addBuilder(
            com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.getDefaultInstance());
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder addImagesBuilder(
          int index) {
        return getImagesFieldBuilder().addBuilder(
            index, com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.getDefaultInstance());
      }
      /**
       * <code>repeated .warmup.entity.Image images = 4;</code>
       */
      public java.util.List<com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder> 
           getImagesBuilderList() {
        return getImagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.depromeet.warmup.grpc.entity.ImageOuterClass.Image, com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder, com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder> 
          getImagesFieldBuilder() {
        if (imagesBuilder_ == null) {
          imagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.depromeet.warmup.grpc.entity.ImageOuterClass.Image, com.depromeet.warmup.grpc.entity.ImageOuterClass.Image.Builder, com.depromeet.warmup.grpc.entity.ImageOuterClass.ImageOrBuilder>(
                  images_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          images_ = null;
        }
        return imagesBuilder_;
      }

      private com.depromeet.warmup.grpc.entity.UserOuterClass.User owner_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.depromeet.warmup.grpc.entity.UserOuterClass.User, com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder, com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder> ownerBuilder_;
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       * @return Whether the owner field is set.
       */
      public boolean hasOwner() {
        return ownerBuilder_ != null || owner_ != null;
      }
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       * @return The owner.
       */
      public com.depromeet.warmup.grpc.entity.UserOuterClass.User getOwner() {
        if (ownerBuilder_ == null) {
          return owner_ == null ? com.depromeet.warmup.grpc.entity.UserOuterClass.User.getDefaultInstance() : owner_;
        } else {
          return ownerBuilder_.getMessage();
        }
      }
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       */
      public Builder setOwner(com.depromeet.warmup.grpc.entity.UserOuterClass.User value) {
        if (ownerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          owner_ = value;
          onChanged();
        } else {
          ownerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       */
      public Builder setOwner(
          com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder builderForValue) {
        if (ownerBuilder_ == null) {
          owner_ = builderForValue.build();
          onChanged();
        } else {
          ownerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       */
      public Builder mergeOwner(com.depromeet.warmup.grpc.entity.UserOuterClass.User value) {
        if (ownerBuilder_ == null) {
          if (owner_ != null) {
            owner_ =
              com.depromeet.warmup.grpc.entity.UserOuterClass.User.newBuilder(owner_).mergeFrom(value).buildPartial();
          } else {
            owner_ = value;
          }
          onChanged();
        } else {
          ownerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       */
      public Builder clearOwner() {
        if (ownerBuilder_ == null) {
          owner_ = null;
          onChanged();
        } else {
          owner_ = null;
          ownerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       */
      public com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder getOwnerBuilder() {
        
        onChanged();
        return getOwnerFieldBuilder().getBuilder();
      }
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       */
      public com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder getOwnerOrBuilder() {
        if (ownerBuilder_ != null) {
          return ownerBuilder_.getMessageOrBuilder();
        } else {
          return owner_ == null ?
              com.depromeet.warmup.grpc.entity.UserOuterClass.User.getDefaultInstance() : owner_;
        }
      }
      /**
       * <code>.warmup.entity.User owner = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.depromeet.warmup.grpc.entity.UserOuterClass.User, com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder, com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder> 
          getOwnerFieldBuilder() {
        if (ownerBuilder_ == null) {
          ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.depromeet.warmup.grpc.entity.UserOuterClass.User, com.depromeet.warmup.grpc.entity.UserOuterClass.User.Builder, com.depromeet.warmup.grpc.entity.UserOuterClass.UserOrBuilder>(
                  getOwner(),
                  getParentForChildren(),
                  isClean());
          owner_ = null;
        }
        return ownerBuilder_;
      }

      private long createdDate_ ;
      /**
       * <code>int64 created_date = 6;</code>
       * @return The createdDate.
       */
      public long getCreatedDate() {
        return createdDate_;
      }
      /**
       * <code>int64 created_date = 6;</code>
       * @param value The createdDate to set.
       * @return This builder for chaining.
       */
      public Builder setCreatedDate(long value) {
        
        createdDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 created_date = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreatedDate() {
        
        createdDate_ = 0L;
        onChanged();
        return this;
      }

      private long lastModifiedDate_ ;
      /**
       * <code>int64 last_modified_date = 7;</code>
       * @return The lastModifiedDate.
       */
      public long getLastModifiedDate() {
        return lastModifiedDate_;
      }
      /**
       * <code>int64 last_modified_date = 7;</code>
       * @param value The lastModifiedDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastModifiedDate(long value) {
        
        lastModifiedDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_modified_date = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastModifiedDate() {
        
        lastModifiedDate_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:warmup.entity.Item)
    }

    // @@protoc_insertion_point(class_scope:warmup.entity.Item)
    private static final com.depromeet.warmup.grpc.entity.ItemOuterClass.Item DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.depromeet.warmup.grpc.entity.ItemOuterClass.Item();
    }

    public static com.depromeet.warmup.grpc.entity.ItemOuterClass.Item getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Item>
        PARSER = new com.google.protobuf.AbstractParser<Item>() {
      @java.lang.Override
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Item(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Item> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.depromeet.warmup.grpc.entity.ItemOuterClass.Item getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_warmup_entity_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_warmup_entity_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021entity/item.proto\022\rwarmup.entity\032\022enti" +
      "ty/image.proto\032\021entity/user.proto\032\030type/" +
      "barter_status.proto\"\327\001\n\004Item\022\014\n\004name\030\001 \001" +
      "(\t\022\023\n\013description\030\002 \001(\t\0220\n\rbarter_status" +
      "\030\003 \001(\0162\031.warmup.type.BarterStatus\022$\n\006ima" +
      "ges\030\004 \003(\0132\024.warmup.entity.Image\022\"\n\005owner" +
      "\030\005 \001(\0132\023.warmup.entity.User\022\024\n\014created_d" +
      "ate\030\006 \001(\003\022\032\n\022last_modified_date\030\007 \001(\003B\"\n" +
      " com.depromeet.warmup.grpc.entityb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.depromeet.warmup.grpc.entity.ImageOuterClass.getDescriptor(),
          com.depromeet.warmup.grpc.entity.UserOuterClass.getDescriptor(),
          com.depromeet.warmup.grpc.type.BarterStatusOuterClass.getDescriptor(),
        });
    internal_static_warmup_entity_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_warmup_entity_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_warmup_entity_Item_descriptor,
        new java.lang.String[] { "Name", "Description", "BarterStatus", "Images", "Owner", "CreatedDate", "LastModifiedDate", });
    com.depromeet.warmup.grpc.entity.ImageOuterClass.getDescriptor();
    com.depromeet.warmup.grpc.entity.UserOuterClass.getDescriptor();
    com.depromeet.warmup.grpc.type.BarterStatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
