// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/alarm_type.proto

package com.depromeet.warmup.grpc.type;

public final class AlarmTypeOuterClass {
  private AlarmTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code warmup.type.AlarmType}
   */
  public enum AlarmType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TODO = 0;</code>
     */
    TODO(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TODO = 0;</code>
     */
    public static final int TODO_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AlarmType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AlarmType forNumber(int value) {
      switch (value) {
        case 0: return TODO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AlarmType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AlarmType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AlarmType>() {
            public AlarmType findValueByNumber(int number) {
              return AlarmType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.depromeet.warmup.grpc.type.AlarmTypeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final AlarmType[] VALUES = values();

    public static AlarmType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    AlarmType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:warmup.type.AlarmType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025type/alarm_type.proto\022\013warmup.type*\025\n\t" +
      "AlarmType\022\010\n\004TODO\020\000B \n\036com.depromeet.war" +
      "mup.grpc.typeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
