// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/category_type.proto

package com.depromeet.warmup.grpc.type;

public final class CategoryType {
  private CategoryType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code warmup.type.Categories}
   */
  public enum Categories
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FOOD = 0;</code>
     */
    FOOD(0),
    /**
     * <code>WOMAN = 1;</code>
     */
    WOMAN(1),
    /**
     * <code>MAN = 2;</code>
     */
    MAN(2),
    /**
     * <code>NECESSARIES = 3;</code>
     */
    NECESSARIES(3),
    /**
     * <code>BEAUTY = 4;</code>
     */
    BEAUTY(4),
    /**
     * <code>ELECTRONICS = 5;</code>
     */
    ELECTRONICS(5),
    /**
     * <code>BOOK = 6;</code>
     */
    BOOK(6),
    /**
     * <code>FURNITURE = 7;</code>
     */
    FURNITURE(7),
    /**
     * <code>PET = 8;</code>
     */
    PET(8),
    /**
     * <code>ETC = 9;</code>
     */
    ETC(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FOOD = 0;</code>
     */
    public static final int FOOD_VALUE = 0;
    /**
     * <code>WOMAN = 1;</code>
     */
    public static final int WOMAN_VALUE = 1;
    /**
     * <code>MAN = 2;</code>
     */
    public static final int MAN_VALUE = 2;
    /**
     * <code>NECESSARIES = 3;</code>
     */
    public static final int NECESSARIES_VALUE = 3;
    /**
     * <code>BEAUTY = 4;</code>
     */
    public static final int BEAUTY_VALUE = 4;
    /**
     * <code>ELECTRONICS = 5;</code>
     */
    public static final int ELECTRONICS_VALUE = 5;
    /**
     * <code>BOOK = 6;</code>
     */
    public static final int BOOK_VALUE = 6;
    /**
     * <code>FURNITURE = 7;</code>
     */
    public static final int FURNITURE_VALUE = 7;
    /**
     * <code>PET = 8;</code>
     */
    public static final int PET_VALUE = 8;
    /**
     * <code>ETC = 9;</code>
     */
    public static final int ETC_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Categories valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Categories forNumber(int value) {
      switch (value) {
        case 0: return FOOD;
        case 1: return WOMAN;
        case 2: return MAN;
        case 3: return NECESSARIES;
        case 4: return BEAUTY;
        case 5: return ELECTRONICS;
        case 6: return BOOK;
        case 7: return FURNITURE;
        case 8: return PET;
        case 9: return ETC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Categories>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Categories> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Categories>() {
            public Categories findValueByNumber(int number) {
              return Categories.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.depromeet.warmup.grpc.type.CategoryType.getDescriptor().getEnumTypes().get(0);
    }

    private static final Categories[] VALUES = values();

    public static Categories valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Categories(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:warmup.type.Categories)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030type/category_type.proto\022\013warmup.type*" +
      "\203\001\n\nCategories\022\010\n\004FOOD\020\000\022\t\n\005WOMAN\020\001\022\007\n\003M" +
      "AN\020\002\022\017\n\013NECESSARIES\020\003\022\n\n\006BEAUTY\020\004\022\017\n\013ELE" +
      "CTRONICS\020\005\022\010\n\004BOOK\020\006\022\r\n\tFURNITURE\020\007\022\007\n\003P" +
      "ET\020\010\022\007\n\003ETC\020\tB \n\036com.depromeet.warmup.gr" +
      "pc.typeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
